/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface BountiesMetaTxRelayerInterface extends utils.Interface {
  functions: {
    "bountiesContract()": FunctionFragment;
    "metaAcceptFulfillment(bytes,uint256,uint256,uint256,uint256[],uint256)": FunctionFragment;
    "metaAddApprovers(bytes,uint256,uint256,address[],uint256)": FunctionFragment;
    "metaAddIssuers(bytes,uint256,uint256,address[],uint256)": FunctionFragment;
    "metaChangeApprover(bytes,uint256,uint256,uint256,address,uint256)": FunctionFragment;
    "metaChangeBounty(bytes,uint256,uint256,address[],address[],string,uint256,uint256)": FunctionFragment;
    "metaChangeData(bytes,uint256,uint256,string,uint256)": FunctionFragment;
    "metaChangeDeadline(bytes,uint256,uint256,uint256,uint256)": FunctionFragment;
    "metaChangeIssuer(bytes,uint256,uint256,uint256,address,uint256)": FunctionFragment;
    "metaContribute(bytes,uint256,uint256,uint256)": FunctionFragment;
    "metaDrainBounty(bytes,uint256,uint256,uint256[],uint256)": FunctionFragment;
    "metaFulfillAndAccept(bytes,uint256,address[],string,uint256,uint256[],uint256)": FunctionFragment;
    "metaFulfillBounty(bytes,uint256,address[],string,uint256)": FunctionFragment;
    "metaIssueAndContribute(bytes,address[],address[],string,uint256,address,uint256,uint256,uint256)": FunctionFragment;
    "metaIssueBounty(bytes,address[],address[],string,uint256,address,uint256,uint256)": FunctionFragment;
    "metaPerformAction(bytes,uint256,string,uint256)": FunctionFragment;
    "metaRefundContribution(bytes,uint256,uint256,uint256)": FunctionFragment;
    "metaRefundContributions(bytes,uint256,uint256,uint256[],uint256)": FunctionFragment;
    "metaRefundMyContributions(bytes,uint256,uint256[],uint256)": FunctionFragment;
    "metaUpdateFulfillment(bytes,uint256,uint256,address[],string,uint256)": FunctionFragment;
    "replayNonce(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "bountiesContract"
      | "metaAcceptFulfillment"
      | "metaAddApprovers"
      | "metaAddIssuers"
      | "metaChangeApprover"
      | "metaChangeBounty"
      | "metaChangeData"
      | "metaChangeDeadline"
      | "metaChangeIssuer"
      | "metaContribute"
      | "metaDrainBounty"
      | "metaFulfillAndAccept"
      | "metaFulfillBounty"
      | "metaIssueAndContribute"
      | "metaIssueBounty"
      | "metaPerformAction"
      | "metaRefundContribution"
      | "metaRefundContributions"
      | "metaRefundMyContributions"
      | "metaUpdateFulfillment"
      | "replayNonce"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "bountiesContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "metaAcceptFulfillment",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaAddApprovers",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaAddIssuers",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaChangeApprover",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaChangeBounty",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaChangeData",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaChangeDeadline",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaChangeIssuer",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaContribute",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaDrainBounty",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaFulfillAndAccept",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaFulfillBounty",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaIssueAndContribute",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaIssueBounty",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaPerformAction",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaRefundContribution",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaRefundContributions",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaRefundMyContributions",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaUpdateFulfillment",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "replayNonce",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "bountiesContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaAcceptFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaAddApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaAddIssuers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaChangeApprover",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaChangeBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaChangeData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaChangeDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaChangeIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaContribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaDrainBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaFulfillAndAccept",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaFulfillBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaIssueAndContribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaIssueBounty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaPerformAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaRefundContribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaRefundContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaRefundMyContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "metaUpdateFulfillment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replayNonce",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BountiesMetaTxRelayer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BountiesMetaTxRelayerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bountiesContract(overrides?: CallOverrides): Promise<[string]>;

    metaAcceptFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaAddApprovers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approvers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaAddIssuers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaChangeApprover(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _approver: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaChangeBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaChangeData(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaChangeDeadline(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaChangeIssuer(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuerIdToChange: PromiseOrValue<BigNumberish>,
      _newIssuer: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaContribute(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaDrainBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _amounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaFulfillAndAccept(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaFulfillBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaIssueAndContribute(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaIssueBounty(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaPerformAction(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaRefundContribution(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaRefundContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaRefundMyContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaUpdateFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    replayNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  bountiesContract(overrides?: CallOverrides): Promise<string>;

  metaAcceptFulfillment(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _fulfillmentId: PromiseOrValue<BigNumberish>,
    _approverId: PromiseOrValue<BigNumberish>,
    _tokenAmounts: PromiseOrValue<BigNumberish>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaAddApprovers(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _approvers: PromiseOrValue<string>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaAddIssuers(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _issuers: PromiseOrValue<string>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaChangeApprover(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _approverId: PromiseOrValue<BigNumberish>,
    _approver: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaChangeBounty(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _issuers: PromiseOrValue<string>[],
    _approvers: PromiseOrValue<string>[],
    _data: PromiseOrValue<string>,
    _deadline: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaChangeData(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaChangeDeadline(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _deadline: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaChangeIssuer(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _issuerIdToChange: PromiseOrValue<BigNumberish>,
    _newIssuer: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaContribute(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaDrainBounty(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _amounts: PromiseOrValue<BigNumberish>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaFulfillAndAccept(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _fulfillers: PromiseOrValue<string>[],
    _data: PromiseOrValue<string>,
    _approverId: PromiseOrValue<BigNumberish>,
    _tokenAmounts: PromiseOrValue<BigNumberish>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaFulfillBounty(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _fulfillers: PromiseOrValue<string>[],
    _data: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaIssueAndContribute(
    signature: PromiseOrValue<BytesLike>,
    _issuers: PromiseOrValue<string>[],
    _approvers: PromiseOrValue<string>[],
    _data: PromiseOrValue<string>,
    _deadline: PromiseOrValue<BigNumberish>,
    _token: PromiseOrValue<string>,
    _tokenVersion: PromiseOrValue<BigNumberish>,
    _depositAmount: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaIssueBounty(
    signature: PromiseOrValue<BytesLike>,
    _issuers: PromiseOrValue<string>[],
    _approvers: PromiseOrValue<string>[],
    _data: PromiseOrValue<string>,
    _deadline: PromiseOrValue<BigNumberish>,
    _token: PromiseOrValue<string>,
    _tokenVersion: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaPerformAction(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _data: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaRefundContribution(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _contributionId: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaRefundContributions(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _issuerId: PromiseOrValue<BigNumberish>,
    _contributionIds: PromiseOrValue<BigNumberish>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaRefundMyContributions(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _contributionIds: PromiseOrValue<BigNumberish>[],
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaUpdateFulfillment(
    _signature: PromiseOrValue<BytesLike>,
    _bountyId: PromiseOrValue<BigNumberish>,
    _fulfillmentId: PromiseOrValue<BigNumberish>,
    _fulfillers: PromiseOrValue<string>[],
    _data: PromiseOrValue<string>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  replayNonce(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    bountiesContract(overrides?: CallOverrides): Promise<string>;

    metaAcceptFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaAddApprovers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approvers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaAddIssuers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaChangeApprover(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _approver: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaChangeBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaChangeData(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaChangeDeadline(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaChangeIssuer(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuerIdToChange: PromiseOrValue<BigNumberish>,
      _newIssuer: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaContribute(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaDrainBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _amounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaFulfillAndAccept(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaFulfillBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaIssueAndContribute(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaIssueBounty(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    metaPerformAction(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaRefundContribution(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaRefundContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaRefundMyContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaUpdateFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    replayNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    bountiesContract(overrides?: CallOverrides): Promise<BigNumber>;

    metaAcceptFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaAddApprovers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approvers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaAddIssuers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaChangeApprover(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _approver: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaChangeBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaChangeData(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaChangeDeadline(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaChangeIssuer(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuerIdToChange: PromiseOrValue<BigNumberish>,
      _newIssuer: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaContribute(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaDrainBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _amounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaFulfillAndAccept(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaFulfillBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaIssueAndContribute(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaIssueBounty(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaPerformAction(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaRefundContribution(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaRefundContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaRefundMyContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaUpdateFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    replayNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bountiesContract(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    metaAcceptFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaAddApprovers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approvers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaAddIssuers(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaChangeApprover(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _approverId: PromiseOrValue<BigNumberish>,
      _approver: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaChangeBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaChangeData(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaChangeDeadline(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _deadline: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaChangeIssuer(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _issuerIdToChange: PromiseOrValue<BigNumberish>,
      _newIssuer: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaContribute(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaDrainBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _amounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaFulfillAndAccept(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _approverId: PromiseOrValue<BigNumberish>,
      _tokenAmounts: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaFulfillBounty(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaIssueAndContribute(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _depositAmount: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaIssueBounty(
      signature: PromiseOrValue<BytesLike>,
      _issuers: PromiseOrValue<string>[],
      _approvers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _deadline: PromiseOrValue<BigNumberish>,
      _token: PromiseOrValue<string>,
      _tokenVersion: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaPerformAction(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaRefundContribution(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaRefundContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _issuerId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaRefundMyContributions(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _contributionIds: PromiseOrValue<BigNumberish>[],
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaUpdateFulfillment(
      _signature: PromiseOrValue<BytesLike>,
      _bountyId: PromiseOrValue<BigNumberish>,
      _fulfillmentId: PromiseOrValue<BigNumberish>,
      _fulfillers: PromiseOrValue<string>[],
      _data: PromiseOrValue<string>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    replayNonce(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
