/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721BasicSol from "./ERC721Basic.sol";
export type { erc721BasicSol };
export type { ERC20Token } from "./ERC20Token";
export type { HumanStandardToken } from "./HumanStandardToken";
export type { Migrations } from "./Migrations";
export type { Token } from "./Token";
